version: "3.8"

services:
  ec2dns:
    image: wimomisterx/ec2dns:0.2.0
    command:
      - --bind
      - 0.0.0.0:53
      - --aws-credentials-path
      - /run/secrets/ec2_aws_credentials
    volumes:
      - ./aws-credentials:/run/secrets/ec2dns_aws_credentials
    networks:
      monitoring:
        ipv4_address: 10.0.85.10

  shell:
    image: dersimn/netutils
    entrypoint: '/bin/bash -c "trap : TERM INT; sleep infinity & wait"'
    dns: 10.0.85.10
    networks:
      - default
      - monitoring
    depends_on:
      - ec2dns

networks:
  monitoring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.85.0/28

